---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/trace-collector: "oc-collector.tracing:55678"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminus
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminus
  template:
    metadata:
      labels:
        app: terminus
    spec:
      containers:
      - name: http-to-grpc
        image: buoyantio/bb:v0.0.5
        args: ["terminus", "--grpc-server-port", "9090", "--response-text", "Hafa Adai"]
        ports:
        - containerPort: 9090
          name: grpc
        resources:
          requests:
            cpu: .1m
            memory: 100Mi
          limits:
            cpu: .25m
            memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: terminus-svc
  namespace: demo-app
spec:
  selector:
    app: terminus
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: http-to-grpc
        image: buoyantio/bb:v0.0.5
        args: ["point-to-point-channel", "--grpc-downstream-server", "terminus-svc:9090", "--h1-server-port", "8080"]
        ports:
        - containerPort: 8080
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: demo-app
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-nginx
  namespace: demo-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: gateway-svc
              servicePort: 8080
---